run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - gocritic
    - gosec
    - exportloopref
    - noctx
    - bodyclose
    - unconvert
    - unparam
    - prealloc

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    check-shadowing: true
  
  gofmt:
    simplify: true
  
  revive:
    severity: warning
    rules:
      - name: exported
        severity: warning
      - name: unused-parameter
        severity: warning
      - name: unreachable-code
        severity: warning
  
  gosec:
    excludes:
      - G104  # Audit errors not checked (we use errcheck for this)
  
  misspell:
    locale: US

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
